#!/usr/bin/env python3
"""Update primary nav across site HTML to the Chronicles 5-item set.

Nav items: Home · About · Insights · Chronicles · Contact
Removes "How We Think" / "What We're Building" from #site-nav.

Skips: docs/, platform/, and generated chronicles/ output (nav there comes from the build).

Insights pages ARE updated for global #site-nav chrome only (Home·About·Insights·Chronicles·Contact).
That is a sitewide nav contract, not an Insights redesign — article bodies/templates stay untouched.

Usage (from lonko-digital-site/):
  python scripts/sync_site_nav.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# docs/ + platform/; chronicles/ nav is generated by build_chronicles.py
SKIP_DIRS = {"docs", "platform", ".git", "node_modules", "chronicles"}

NAV_UL_RE = re.compile(
    r'(<nav\b[^>]*\bid=["\']site-nav["\'][^>]*>\s*)<ul>.*?</ul>(\s*</nav>)',
    re.DOTALL | re.IGNORECASE,
)


def depth_for(path: Path) -> int:
    """Directory depth of the HTML file relative to site root."""
    rel = path.resolve().relative_to(ROOT)
    # index.html at root → 0; about/index.html → 1; a/b/index.html → 2
    return len(rel.parts) - 1


def prefix_for(depth: int) -> str:
    if depth <= 0:
        return ""
    return "../" * depth


def nav_ul(path: Path) -> str:
    depth = depth_for(path)
    p = prefix_for(depth)
    # Detect current section from path
    parts = path.resolve().relative_to(ROOT).parts
    current = None
    if path.name == "index.html" and len(parts) == 1:
        current = "Home"
    elif parts and parts[0] == "about":
        current = "About"
    elif parts and parts[0] == "insights":
        current = "Insights"
    elif parts and parts[0] == "chronicles":
        current = "Chronicles"
    elif parts and parts[0] == "contact":
        current = "Contact"

    def item(label: str, href: str) -> str:
        aria = ' aria-current="page"' if current == label else ""
        return f'          <li><a href="{href}"{aria}>{label}</a></li>'

    home_href = "./" if depth == 0 else p
    about_href = f"{p}about/" if depth else "about/"
    insights_href = f"{p}insights/" if depth else "insights/"
    chronicles_href = f"{p}chronicles/" if depth else "chronicles/"
    contact_href = f"{p}contact/" if depth else "contact/"

    # When already inside the section, prefer ./ for that item
    if current == "About" and depth == 1:
        about_href = "./"
    if current == "Contact" and depth == 1:
        contact_href = "./"
    if current == "Chronicles" and depth == 1:
        chronicles_href = "./"
    if current == "Insights" and depth == 1:
        insights_href = "./"
    if current == "Home" and depth == 0:
        home_href = "./"

    lines = [
        "<ul>",
        item("Home", home_href),
        item("About", about_href),
        item("Insights", insights_href),
        item("Chronicles", chronicles_href),
        item("Contact", contact_href),
        "        </ul>",
    ]
    return "\n".join(lines)


def should_skip(path: Path) -> bool:
    try:
        rel = path.resolve().relative_to(ROOT)
    except ValueError:
        return True
    if any(part in SKIP_DIRS for part in rel.parts):
        return True
    return False


def update_file(path: Path) -> bool:
    original = path.read_text(encoding="utf-8")
    if 'id="site-nav"' not in original and "id='site-nav'" not in original:
        return False
    ul = nav_ul(path)

    def repl(match: re.Match[str]) -> str:
        return f"{match.group(1)}{ul}{match.group(2)}"

    updated, n = NAV_UL_RE.subn(repl, original, count=1)
    if n == 0:
        print(f"  skip (no match): {path.relative_to(ROOT)}")
        return False
    if updated == original:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    changed = 0
    scanned = 0
    for path in sorted(ROOT.rglob("*.html")):
        if should_skip(path):
            continue
        scanned += 1
        if update_file(path):
            changed += 1
            print(f"  updated: {path.relative_to(ROOT)}")
    print(f"sync_site_nav: scanned {scanned}, updated {changed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
